package com.ctfo.generated_src.dao;

import java.util.List;

import com.ctfo.generated_src.bean.InvokeLog;
import com.ctfo.generated_src.bean.InvokeLogExample;
import com.ctfo.generated_src.bean.InvokeLogExampleExtended;

public interface InvokeLogDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	void insert(InvokeLog record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int updateByPrimaryKey(InvokeLog record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int updateByPrimaryKeySelective(InvokeLog record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	List selectByExample(InvokeLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	InvokeLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int deleteByExample(InvokeLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int countByExample(InvokeLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int updateByExampleSelective(InvokeLog record, InvokeLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int updateByExample(InvokeLog record, InvokeLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	List selectByExampleWithPage(InvokeLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	List selectByExampleWithPage(InvokeLogExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	List getKeyBy(InvokeLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	List getKeyBy(InvokeLogExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	int countByExample(InvokeLogExampleExtended example);
}