package com.ctfo.generated_src.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ctfo.generated_src.bean.Triggers;
import com.ctfo.generated_src.bean.TriggersExample;
import com.ctfo.generated_src.bean.TriggersExampleExtended;

public class TriggersDAOImpl extends SqlMapClientDaoSupport implements TriggersDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public TriggersDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public void insert(Triggers record) {
		getSqlMapClientTemplate().insert(
				"QRTZ_TRIGGERS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int updateByPrimaryKeyWithoutBLOBs(Triggers record) {
		int rows = getSqlMapClientTemplate().update(
				"QRTZ_TRIGGERS.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int updateByPrimaryKeyWithBLOBs(Triggers record) {
		int rows = getSqlMapClientTemplate().update(
				"QRTZ_TRIGGERS.abatorgenerated_updateByPrimaryKeyWithBLOBs",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int updateByPrimaryKeySelective(Triggers record) {
		int rows = getSqlMapClientTemplate().update(
				"QRTZ_TRIGGERS.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public List selectByExampleWithoutBLOBs(TriggersExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"QRTZ_TRIGGERS.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public List selectByExampleWithBLOBs(TriggersExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"QRTZ_TRIGGERS.abatorgenerated_selectByExampleWithBLOBs",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public Triggers selectByPrimaryKey(String schedName, String triggerGroup,
			String triggerName) {
		Triggers key = new Triggers() {
		};
		key.setSchedName(schedName);
		key.setTriggerGroup(triggerGroup);
		key.setTriggerName(triggerName);
		Triggers record = (Triggers) getSqlMapClientTemplate().queryForObject(
				"QRTZ_TRIGGERS.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int deleteByExample(TriggersExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"QRTZ_TRIGGERS.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int deleteByPrimaryKey(String schedName, String triggerGroup,
			String triggerName) {
		Triggers key = new Triggers() {
		};
		key.setSchedName(schedName);
		key.setTriggerGroup(triggerGroup);
		key.setTriggerName(triggerName);
		int rows = getSqlMapClientTemplate().delete(
				"QRTZ_TRIGGERS.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int countByExample(TriggersExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"QRTZ_TRIGGERS.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int updateByExampleSelective(Triggers record, TriggersExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("QRTZ_TRIGGERS.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int updateByExampleWithBLOBs(Triggers record, TriggersExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("QRTZ_TRIGGERS.abatorgenerated_updateByExampleWithBLOBs",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int updateByExampleWithoutBLOBs(Triggers record,
			TriggersExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"QRTZ_TRIGGERS.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public List selectByExampleWithPage(TriggersExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"QRTZ_TRIGGERS.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public List selectByExampleWithPage(
			TriggersExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"QRTZ_TRIGGERS.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public List getKeyBy(TriggersExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"QRTZ_TRIGGERS.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public String getNameSpace() {
		return "QRTZ_TRIGGERS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public List getKeyBy(TriggersExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"QRTZ_TRIGGERS.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	public int countByExample(TriggersExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"QRTZ_TRIGGERS.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	private static class UpdateByExampleParms extends TriggersExample {
		private Object record;

		public UpdateByExampleParms(Object record, TriggersExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}