package com.ctfo.generated_src.dao;

import java.util.List;

import com.ctfo.generated_src.bean.Triggers;
import com.ctfo.generated_src.bean.TriggersExample;
import com.ctfo.generated_src.bean.TriggersExampleExtended;

public interface TriggersDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	void insert(Triggers record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int updateByPrimaryKeyWithoutBLOBs(Triggers record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(Triggers record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int updateByPrimaryKeySelective(Triggers record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	List selectByExampleWithoutBLOBs(TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	List selectByExampleWithBLOBs(TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	Triggers selectByPrimaryKey(String schedName, String triggerGroup,
			String triggerName);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int deleteByExample(TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int deleteByPrimaryKey(String schedName, String triggerGroup,
			String triggerName);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int countByExample(TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int updateByExampleSelective(Triggers record, TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int updateByExampleWithBLOBs(Triggers record, TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int updateByExampleWithoutBLOBs(Triggers record, TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	List selectByExampleWithPage(TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	List selectByExampleWithPage(
			TriggersExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	List getKeyBy(TriggersExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	List getKeyBy(TriggersExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_TRIGGERS
	 * @abatorgenerated  Tue Mar 03 16:40:14 CST 2015
	 */
	int countByExample(TriggersExampleExtended example);
}