package com.ctfo.upp.baseservice.dao;

import com.ctfo.base.dao.beans.SimpleCode;
import com.ctfo.base.dao.beans.SimpleCodeExample;
import com.ctfo.base.dao.beans.SimpleCodeExampleExtended;
import java.util.List;

public interface SimpleCodeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	void insert(SimpleCode record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int updateByPrimaryKey(SimpleCode record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int updateByPrimaryKeySelective(SimpleCode record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	List selectByExample(SimpleCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	SimpleCode selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int deleteByExample(SimpleCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int countByExample(SimpleCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int updateByExampleSelective(SimpleCode record, SimpleCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int updateByExample(SimpleCode record, SimpleCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	List selectByExampleWithPage(SimpleCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	List selectByExampleWithPage(SimpleCodeExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	List getKeyBy(SimpleCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	List getKeyBy(SimpleCodeExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SIMPLE_CODE
	 * @abatorgenerated  Wed Nov 05 15:07:04 CST 2014
	 */
	int countByExample(SimpleCodeExampleExtended example);
}