package com.ctfo.upp.baseservice.dao;

import com.ctfo.base.dao.beans.UPParam;
import com.ctfo.base.dao.beans.UPParamExample;
import com.ctfo.base.dao.beans.UPParamExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UPParamDAOImpl extends SqlMapClientDaoSupport implements UPParamDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public UPParamDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public void insert(UPParam record) {
		getSqlMapClientTemplate().insert("TB_UPP_PARAM.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int updateByPrimaryKey(UPParam record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PARAM.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int updateByPrimaryKeySelective(UPParam record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PARAM.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public List selectByExample(UPParamExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PARAM.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public UPParam selectByPrimaryKey(String id) {
		UPParam key = new UPParam() {
		};
		key.setId(id);
		UPParam record = (UPParam) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PARAM.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int deleteByExample(UPParamExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PARAM.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		UPParam key = new UPParam() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PARAM.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int countByExample(UPParamExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PARAM.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int updateByExampleSelective(UPParam record, UPParamExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PARAM.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int updateByExample(UPParam record, UPParamExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PARAM.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public List selectByExampleWithPage(UPParamExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PARAM.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public List selectByExampleWithPage(UPParamExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PARAM.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public List getKeyBy(UPParamExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PARAM.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public String getNameSpace() {
		return "TB_UPP_PARAM";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public List getKeyBy(UPParamExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PARAM.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	public int countByExample(UPParamExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PARAM.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_PARAM
	 * @abatorgenerated  Tue Nov 04 13:25:26 CST 2014
	 */
	private static class UpdateByExampleParms extends UPParamExample {
		private Object record;

		public UpdateByExampleParms(Object record, UPParamExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}