package com.ctfo.upp.baseservice.dao;

import com.ctfo.base.dao.beans.UPPlatform;
import com.ctfo.base.dao.beans.UPPlatformExample;
import com.ctfo.base.dao.beans.UPPlatformExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UPPlatformDAOImpl extends SqlMapClientDaoSupport implements UPPlatformDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public UPPlatformDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public void insert(UPPlatform record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_STORE_MESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int updateByPrimaryKey(UPPlatform record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_STORE_MESS.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int updateByPrimaryKeySelective(UPPlatform record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_STORE_MESS.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public List selectByExample(UPPlatformExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_MESS.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public UPPlatform selectByPrimaryKey(String id) {
		UPPlatform key = new UPPlatform() {
		};
		key.setId(id);
		UPPlatform record = (UPPlatform) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_STORE_MESS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int deleteByExample(UPPlatformExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_STORE_MESS.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		UPPlatform key = new UPPlatform() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_STORE_MESS.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int countByExample(UPPlatformExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_STORE_MESS.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int updateByExampleSelective(UPPlatform record,
			UPPlatformExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_STORE_MESS.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int updateByExample(UPPlatform record, UPPlatformExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_STORE_MESS.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public List selectByExampleWithPage(UPPlatformExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_MESS.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public List selectByExampleWithPage(
			UPPlatformExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_STORE_MESS.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public List getKeyBy(UPPlatformExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_MESS.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public String getNameSpace() {
		return "TB_UPP_STORE_MESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public List getKeyBy(UPPlatformExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_MESS.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	public int countByExample(UPPlatformExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_STORE_MESS.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	private static class UpdateByExampleParms extends UPPlatformExample {
		private Object record;

		public UpdateByExampleParms(Object record, UPPlatformExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}