package com.ctfo.upp.baseservice.dao;

import com.ctfo.base.dao.beans.UPPlatformCallbackUrl;
import com.ctfo.base.dao.beans.UPPlatformCallbackUrlExample;
import com.ctfo.base.dao.beans.UPPlatformCallbackUrlExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UPPlatformCallbackUrlDAOImpl extends SqlMapClientDaoSupport implements UPPlatformCallbackUrlDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public UPPlatformCallbackUrlDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public void insert(UPPlatformCallbackUrl record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int updateByPrimaryKey(UPPlatformCallbackUrl record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int updateByPrimaryKeySelective(UPPlatformCallbackUrl record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_STORE_URL_MESS.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public List selectByExample(UPPlatformCallbackUrlExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public UPPlatformCallbackUrl selectByPrimaryKey(String id) {
		UPPlatformCallbackUrl key = new UPPlatformCallbackUrl() {
		};
		key.setId(id);
		UPPlatformCallbackUrl record = (UPPlatformCallbackUrl) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_STORE_URL_MESS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int deleteByExample(UPPlatformCallbackUrlExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		UPPlatformCallbackUrl key = new UPPlatformCallbackUrl() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_UPP_STORE_URL_MESS.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int countByExample(UPPlatformCallbackUrlExample example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_STORE_URL_MESS.abatorgenerated_countByExample",
						example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int updateByExampleSelective(UPPlatformCallbackUrl record,
			UPPlatformCallbackUrlExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_STORE_URL_MESS.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int updateByExample(UPPlatformCallbackUrl record,
			UPPlatformCallbackUrlExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public List selectByExampleWithPage(UPPlatformCallbackUrlExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public List selectByExampleWithPage(
			UPPlatformCallbackUrlExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_STORE_URL_MESS.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public List getKeyBy(UPPlatformCallbackUrlExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public String getNameSpace() {
		return "TB_UPP_STORE_URL_MESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public List getKeyBy(UPPlatformCallbackUrlExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	public int countByExample(UPPlatformCallbackUrlExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_STORE_URL_MESS.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	private static class UpdateByExampleParms extends
			UPPlatformCallbackUrlExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				UPPlatformCallbackUrlExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}