package com.ctfo.upp.baseservice.dao;

import com.ctfo.base.dao.beans.UPPlatformCallbackUrl;
import com.ctfo.base.dao.beans.UPPlatformCallbackUrlExample;
import com.ctfo.base.dao.beans.UPPlatformCallbackUrlExampleExtended;
import java.util.List;

public interface UPPlatformCallbackUrlDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	void insert(UPPlatformCallbackUrl record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int updateByPrimaryKey(UPPlatformCallbackUrl record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int updateByPrimaryKeySelective(UPPlatformCallbackUrl record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	List selectByExample(UPPlatformCallbackUrlExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	UPPlatformCallbackUrl selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int deleteByExample(UPPlatformCallbackUrlExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int countByExample(UPPlatformCallbackUrlExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int updateByExampleSelective(UPPlatformCallbackUrl record,
			UPPlatformCallbackUrlExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int updateByExample(UPPlatformCallbackUrl record,
			UPPlatformCallbackUrlExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	List selectByExampleWithPage(UPPlatformCallbackUrlExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	List selectByExampleWithPage(
			UPPlatformCallbackUrlExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	List getKeyBy(UPPlatformCallbackUrlExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	List getKeyBy(UPPlatformCallbackUrlExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_URL_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:27 CST 2014
	 */
	int countByExample(UPPlatformCallbackUrlExampleExtended example);
}