package com.ctfo.upp.baseservice.dao;

import com.ctfo.base.dao.beans.UPPlatform;
import com.ctfo.base.dao.beans.UPPlatformExample;
import com.ctfo.base.dao.beans.UPPlatformExampleExtended;
import java.util.List;

public interface UPPlatformDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	void insert(UPPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int updateByPrimaryKey(UPPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int updateByPrimaryKeySelective(UPPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	List selectByExample(UPPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	UPPlatform selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int deleteByExample(UPPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int countByExample(UPPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int updateByExampleSelective(UPPlatform record, UPPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int updateByExample(UPPlatform record, UPPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	List selectByExampleWithPage(UPPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	List selectByExampleWithPage(UPPlatformExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	List getKeyBy(UPPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	List getKeyBy(UPPlatformExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_STORE_MESS
	 * @abatorgenerated  Tue Nov 04 13:25:25 CST 2014
	 */
	int countByExample(UPPlatformExampleExtended example);
}