package com.ctfo.generated_src.bean;

import javax.xml.bind.annotation.XmlElement;

import com.ctfo.quartz.bean.BaseSerializable;

public class InvokeLog extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column QUARTZ.QRTZ_INVOKE_LOG.ID DB Comment: 
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	@XmlElement(name = "", required = false)
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column QUARTZ.QRTZ_INVOKE_LOG.STATUS DB Comment: 
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	@XmlElement(name = "", required = false)
	private String status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_TIME DB Comment: 
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	@XmlElement(name = "", required = false)
	private Long triggerTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_NAME DB Comment: 
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	@XmlElement(name = "", required = false)
	private String triggerName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_GROUP DB Comment: 
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	@XmlElement(name = "", required = false)
	private String triggerGroup;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column QUARTZ.QRTZ_INVOKE_LOG.ID
	 * @return  the value of QUARTZ.QRTZ_INVOKE_LOG.ID
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column QUARTZ.QRTZ_INVOKE_LOG.ID
	 * @param id  the value for QUARTZ.QRTZ_INVOKE_LOG.ID
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public static String fieldId() {
		return "ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column QUARTZ.QRTZ_INVOKE_LOG.STATUS
	 * @return  the value of QUARTZ.QRTZ_INVOKE_LOG.STATUS
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column QUARTZ.QRTZ_INVOKE_LOG.STATUS
	 * @param status  the value for QUARTZ.QRTZ_INVOKE_LOG.STATUS
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public static String fieldStatus() {
		return "STATUS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_TIME
	 * @return  the value of QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_TIME
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public Long getTriggerTime() {
		return triggerTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_TIME
	 * @param triggerTime  the value for QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_TIME
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public void setTriggerTime(Long triggerTime) {
		this.triggerTime = triggerTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public static String fieldTriggerTime() {
		return "TRIGGER_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_NAME
	 * @return  the value of QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_NAME
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public String getTriggerName() {
		return triggerName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_NAME
	 * @param triggerName  the value for QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_NAME
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public static String fieldTriggerName() {
		return "TRIGGER_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_GROUP
	 * @return  the value of QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_GROUP
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public String getTriggerGroup() {
		return triggerGroup;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_GROUP
	 * @param triggerGroup  the value for QUARTZ.QRTZ_INVOKE_LOG.TRIGGER_GROUP
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public void setTriggerGroup(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public static String fieldTriggerGroup() {
		return "TRIGGER_GROUP";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public InvokeLog() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public static String tableName() {
		return "QRTZ_INVOKE_LOG";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table QUARTZ.QRTZ_INVOKE_LOG
	 * @abatorgenerated  Tue Mar 03 16:40:13 CST 2015
	 */
	public static String daoInterface() {
		return "com.ctfo.quartz.dao.InvokeLogDAO";
	}
}